### ISSUE TITLE
Request: option in right-click menu to do a player lookup in LFG UI 

### ISSUE THREAD

**Issue by rideekulous** [Vloer/keycount#12]
Would be nice to perform a player lookup from the right-click menu when looking at players in LFG queue. Both when seeking a group, or listing one.

Similar to "Copy Radier.IO URL" in the screenshot here.

![image](https://github.com/Vloer/keycount/assets/165203372/fe07c138-6260-4834-bcf9-27495da85c3d)

**Comment by Vloer** [comment]
I am currently working on this but don't have too much time atm. Will be implemented at some point (hopefully soon)

**Comment by Vloer** [comment]
Added in alpha release https://github.com/Vloer/keycount/releases/tag/v0.8-alpha
If you don't mind, please download the alpha version (you have to manually select version via curseforge) and see if this works correctly. 

Note: the popup only shows when data is available (you can test this on yourself)

**Comment by derek-shnosh** [comment]
I will test this later, but initial thought is that the menu option should always be there for efficiency (and other reasons).

Correct me if I'm wrong regarding the current described implementation, but it seems the addon would be performing a lookup every time a right-click (on a valid object) occurs, regardless of whether or not the user clicks the menu option. Ideally the lookup should only occur if the user actually selects the option.

This may not be an immediate concern due to the size of the data being parted initially, but as it grows over time it could introduce even a small hit on resources that shouldn't otherwise be consumed.

**Comment by rideekulous** [comment]
I will test this later, but my initial thought is that the menu option should always be there and the lookup should only happen if it is selected, primarily for efficiency.

Correct me if I'm wrong regarding the current described implementation, but it seems the addon would need to perform a lookup every time a right-click (on a valid object) occurs in order enable the menu option, regardless of whether or not the user selects the menu option. 

For efficiency, ideally the lookup should only occur if the user actually selects the option. This may not be an immediate concern due to the size of the data being parsed initially, but as it grows over time this could introduce even a small hit on resources that shouldn't otherwise be consumed.

**Comment by Vloer** [comment]
Im aware of the bowl of spaghetti currently being thrown around; this was the easiest way to implement the menu only showing up when data is available. The first lookup should be performant enough until like a 100k players grouped with, the addon will require other optimizations way before that so it's not really an issue atm. I'm going to check wtih some other people if they prefer the option being always visible or just when data is avialable.

Thanks for the feedback
